---
spring:
  application:
    name: video-platform
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
minio:
  url: http://localhost
  port: 9000
  user: minio
  password: minio123
  bucket: videos
