---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/videoplatform
    username: video
    password: video
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

ffmpeg:
  path: /opt/homebrew/bin/ffmpeg