package com.sebastianhauss.videoplatform.exception;

public enum ErrorCode {

    VIDEO_NOT_FOUND,
    USER_NOT_FOUND,

    DUPLICATE_USERNAME,
    DUPLICATE_EMAIL,

    UNAUTHORIZED,

    STORAGE_UPLOAD_FAILED,
    STORAGE_DOWNLOAD_FAILED,
    STORAGE_DELETE_FAILED,

    VALIDATION_ERROR,
    INTERNAL_ERROR
}
